### ISSUE TITLE
Hutool-db操作异常

### ISSUE THREAD

**Issue by ThounderStruck** [dromara/hutool#2394]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
db.query(sql) 操作会给sql中的表添加当前数据源连接的库名前缀，即表名会变成【库名.表名】
如果sql中的表已经加上库名前缀，则执行报错
![image](https://user-images.githubusercontent.com/33996112/174484545-cf20c19f-b058-49fa-ab58-de755e0a499c.png)

**Comment by looly** [comment]
啊，麻烦检查下你的逻辑代码，这个方法没有添加数据源前缀的任何逻辑啊。
