### ISSUE TITLE
ObjUtil能否添加getIfNotNull方法

### ISSUE THREAD

**Issue by fickleness-youth** [dromara/hutool#3522]
```
/**
     * 如果指定的对象不为 null,则应用提供的映射函数并返回结果,否则返回 null。
     *
     * @param obj    要检查的对象
     * @param mapper 要应用的映射函数
     * @param <T>    输入对象的类型
     * @param <R>    映射函数的返回类型
     * @return 映射函数的结果,如果输入对象为 null,则返回 null
     */
    public static <T, R> R getIfNotNull(T obj, Function<T, R> mapper) {
        return (obj != null) ? mapper.apply(obj) : null;
    }
```

主要是为了提供一个安全的get方法，避免空指针异常

**Comment by VampireAchao** [comment]
使用`Opt.ofNullable(new Object()).map(Object::hashCode).get()`

**Comment by fickleness-youth** [comment]
> 使用`Opt.ofNullable(new Object()).map(Object::hashCode).get()`

其实就是想把这个再稍微封装下，精简一些

**Comment by looly** [comment]
@fickleness-youth ObjUtil.defaultIfNull

**Comment by fickleness-youth** [comment]
> @fickleness-youth ObjUtil.defaultIfNull

含义正好相反了，defautIfNull是为null才执行

**Comment by looly** [comment]
![image](https://github.com/dromara/hutool/assets/1432613/a0d4f53d-7b9b-4d34-9da9-34bef76026e6)

**Comment by looly** [comment]
确实defautIfNull不太容易理解。

6.0.0-M12增加`ObjUtil.apply`方法

**Comment by fickleness-youth** [comment]
> 确实defautIfNull不太容易理解。
> 
> 6.0.0-M12增加`ObjUtil.apply`方法

好的，多谢
